# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 344f3f0975fa8155442f61ba14d98417a93adc7b2012fa43caff8f25f909d270c26f9dfeed5ea656c93ef1164d539c3a28865afcc8ef75b434f8ead1f379c33d

test:
  secret_key_base: 00d1005f26651c898a0c21d4e1d190876cf8c59f425dc461043acfe851d1a2ce7c6b8a644e89daac21f2a1119e56779f9cd653e0727513ce9901836fdfed3a2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
